config/routes.rb
Rails
  .application
  .routes
  .draw do
    devise_for :users

    scope module: :users do
      resources :todo_lists do
        resources :todo_items do
          member { patch :completed }
        end
      end

      get 'incomplete', to: 'todo_lists#incomplete'
    end

    root 'users/todo_lists#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  validates :description, presence: true

  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 3 }

  extend FriendlyId

  friendly_id :title, use: :slugged 

  has_many :todo_items, dependent: :delete_all

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :timeoutable

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  validate :validate_username

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login

  has_many :todos
  has_many :todo_lists

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pagy::Backend

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]

    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs 
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/users/todo_items_controller.rb
module Users
  class TodoItemsController < UsersController 
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]

    def create
      @todo_item = @todo_list.todo_items.create(todo_item_params)

      if @todo_item.save
        redirect_to @todo_list, notice: 'New Task created!'
      else
        redirect_to new_todo_list_todo_item_path
      end
    end

    def update
      @todo_item.update_attribute(:completed, false)

      redirect_to @todo_list, notice: 'Task marked incomplete'
    end

    def destroy
      if @todo_item.destroy
        flash[:success] = 'Task successfully deleted.'
      else
        flash[:error] = 'Task cannot be deleted'
      end

      redirect_to @todo_list, notice: 'Task Deleted!'
    end

    def completed
      @todo_item.update_attribute(:completed, true)

      redirect_to @todo_list, notice: 'Task Completed!'
    end

    private

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def set_todo_list
      @todo_list = TodoList.friendly.find(params[:todo_list_id])
    end

    def todo_item_params
      params.require(:todo_item).permit(:description)
    end
  end
end

app/controllers/users/todo_lists_controller.rb
module Users
  class TodoListsController < UsersController 
    before_action :set_todo_list, except: %i[index new create incomplete]

    def index
      if current_user
        @pagy, @todo_lists = pagy(current_user.todo_lists.order(created_at: :desc), items: 10)
        @today = Time.new.strftime('%d of %B, %Y')
      end
    end

    def new
      @todo_list = TodoList.new
    end

    def create
      @todo_list = current_user.todo_lists.new(todo_list_params)

      if @todo_list.save
        redirect_to todo_lists_path, notice: 'New Todo-List Successfully Created'
      else
        redirect_to new_todo_list_path, alert: 'Something went wrong...'
      end
    end

    def show; end

    def edit; end

    def incomplete
      @pagy, @incomplete_lists = pagy(current_user.todo_lists.where(completed: false).order(created_at: :desc), items:10) 
      @today = Time.new.strftime('%d of %B, %Y')
    end

    def update
      if @todo_list.update(todo_list_params)
        if @todo_list.completed == true
          redirect_to todo_lists_path, notice: 'Todo-List Marked Complete!'
        elsif @todo_list.completed == false
          redirect_to todo_lists_path, notice: 'Todo-List Marked Incomplete!'
        end
      else
        redirect_to edit_todo_list_path, notice: 'Something went wrong...'
      end
    end

    def destroy
      @todo_list.destroy

      redirect_to todo_lists_path, alert: 'List successfully deleted!'
    end

    private

    def set_todo_list
      @todo_list = TodoList.friendly.find(params[:id])
    end

    def set_incomplete_todo_list
      @incomplete_lists = TodoList.find_by(completed: false)
    end

    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :completed)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper; end

app/helpers/todo_lists_helper.rb
module TodoListsHelper; end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ToDo Classic</a>

  <div class="collapse navbar-collapse w-200 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item p-2"><%= link_to "Signed in as #{current_user.username}", edit_user_registration_path %>
        <li class="nav-item p-2"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <li class="nav-item p-2">
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
        <li class="nav-item ml-auto p-2" >
          <%= link_to "Sign In", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoClassic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mb-4">
      <%= render partial: 'layouts/nav' %>
    </div>

    <div class="container">
      <% if notice %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>

      <div class="mt-4">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/todo_items/_form.html.erb
<div class="container">
  <%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
    <div class="form-group"> 
      <div class="d-flex row justify-content-between">
        <%= f.text_field :description, 
          class: "form-control", style: "width: 85.5%;",
          placeholder: "New Task"
        %>
        <%= f.submit "Create Task", class: "btn btn-success btn-sm" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/todo_items/_todo_item.html.erb
<div class="container" style="width: 100%;">
  <div class="d-flex col justify-content-between mx-auto mb-2">
    <% if todo_item.completed %>
      <div class="justify-content-between" style="color: gray; font-style: italic; width: 90%">
        <span class="pr-2">
          <i class="fas fa-check-circle fa-2x" style="color:green;"></i>
        </span>
        <del><%= todo_item.description %></del>
      </div>
    <% else %>
      <p style="width: 90%;"><%= todo_item.description %></p>
    <% end %>

    <div class="d-flex row justify-content-between">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete do %>
        <span class="pr-2">
          <i class="fas fa-times-circle fa-2x" style="color:red;"></i>
        </span>
      <% end %>
      <% if todo_item.completed %>
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id),
          method: :patch do
        %>
          <span class="pr-2">
            <i class="fas fa-trash-restore fa-2x" style="color:gray;"></i>
          </span>
        <% end %>
      <% else %>
        <%= link_to completed_todo_list_todo_item_path(@todo_list, todo_item.id),
          method: :patch do
        %>
          <span class="pr-2">
            <i class="fas fa-check-square fa-2x" style="color:green;"></i>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/todo_lists/_form.html.erb
<div class="card" style="width: 70%">
  <%= form_with model: @todo_list do |form| %>
    <div class="card-header">
      <% if current_page?(action: :new) %>
        <h2>Add New To-Do List</h2>
      <% elsif current_page?(action: :show) %>
        <h2><%= @todo_list.title %></h2>
      <% elsif current_page?(action: :edit) %>
        <h2>Edit <%= @todo_list.title %></h2>
      <% end %>
    </div>

    <div class="card-body">
      <div class="form-group">
        <%= form.label :title, "Title" %>
        <%= form.text_field :title, class: "form-control" %>

        <% @todo_list.errors.full_messages_for(:title).each do |error| %>
          <div><%= error %></div>
        <% end %>
      </div>

      <div class="form-group">
        <%= form.label :description, "Description" %>
        <%= form.text_area :description, rows: 6, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.check_box :completed %>
        <%= form.label :completed, "Mark as complete" %>
      </div>
    </div>

    <div class="card-footer">
      <div class="row justify-content-between mx-auto">
        <%= form.submit class: "btn btn-success" %>
        <%= link_to "Cancel", @todo_list, class: "btn btn-secondary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/users/todo_lists/_paggy.html.erb
<%== pagy_bootstrap_nav(@pagy) %>

app/views/users/todo_lists/_todo_list_action.html.erb
<td style="width: 19.33%;">
  <div class="d-inline-flex pr-2">
    <div class="mr-2">
      <% if list.completed %>
        <%= form_for(list) do |f| %>
          <%= f.check_box :completed, hidden: true, checked: false %>
          <%= button_tag type: :submit, class: "btn btn-primary btn-sm" do %>
            <span>
              <i class="fas fa-trash-restore fa-2x"></i>
            </span>
          <% end %>
        <% end %>
      <% else %>
        <%= form_for(list) do |f| %>
          <%= f.check_box :completed, hidden: true, checked: true %>
          <%= button_tag type: :submit, class: "btn btn-success btn-sm" do %>
            <span>
              <i class="fas fa-check-square fa-2x"></i>
            </span>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <%= link_to list, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } do %>
      <span>
        <i class="fas fa-times-circle fa-2x"></i>
      </span>
    <% end %>
  </div>
</td>

app/views/users/todo_lists/_todo_list_description.html.erb
<% if list.completed %>
  <td style="width: 45.33%;">
    <% if list.description.length > 70 %>
      <del><%=
        link_to list.description.split(' ').each_with_object('') { |x, ob| break ob unless (ob.length + ' '.length + x.length <= 70); ob << (' ' + x) }.strip + '...',
        list, style: "color: gray; font-style: italic" 
      %></del>
    <% else %>
      <del><%= link_to list.description, list, style: "color: gray; font-style: italic;" %></del>
    <% end %>
  </td>
<% else %>
  <td style="width: 45.33%;">
    <% if list.description.length > 70 %>
      <%=
        link_to list.description.split(' ').each_with_object('') { |x, ob| break ob unless (ob.length + ' '.length + x.length <= 70); ob << (' ' + x) }.strip + '...',
        list 
      %>
    <% else %>
      <%= link_to list.description, list %>
    <% end %>
  </td>
<% end %>

app/views/users/todo_lists/_todo_list_status.html.erb
<td style="width: 15%">
  <% if list.completed %>
    <i class="fas fa-check-circle fa-2x" style="color:green;"></i>
  <% else %>
    <span>
      <%= link_to edit_todo_list_path(list) do %>
        <span>
          <i class="fas fa-spinner fa-2x"></i>
        </span>
      <% end %>
    </span>
  <% end %>
</td>

app/views/users/todo_lists/_todo_list_title.html.erb
<% if list.completed %>
  <td style="width: 20.33%;">
    <del><%= link_to list.title, list, style: "color: gray; font-style: italic" %></del>
  </td>
<% else %>
  <td style="width: 20.33%;">
    <%= link_to list.title, list %>
  </td>
<% end %>

app/views/users/todo_lists/edit.html.erb
<div class="col">
  <div class="row justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/users/todo_lists/incomplete.html.erb
<% if current_user %>
  <div class="container mt-4" style="width: 100%;">
    <div class="d-flex justify-content-between mb-4">
      <div class="btn-group" role="group">
        <span class="btn btn-info">Today: <%= @today %></span>
        <span class="btn btn-outline-primary">Incomplete To-Do Lists</span>
      </div>

      <div class="btn-group" role="group">
        <%= link_to "Back", todo_lists_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
      <% @incomplete_lists.each do |list| %>
        <tr>
        </tr>
      <% end %>

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <td scope="col"><b>Title</b></td>
          <td scope="col"><b>Description</b></td>
          <td scope="col"><b>Action</b></td>
          <td scope="col"><b>Status</b></td>
        </tr>
      </thead>

      <tbody>
        <% @incomplete_lists.each do |list| %>
          <tr>
            <%= render partial: "todo_list_title", locals: { list: list } %>
            <%= render partial: "todo_list_description", locals: { list: list } %>
            <%= render partial: "todo_list_action", locals: { list: list } %>
            <%= render partial: "todo_list_status", locals: { list: list } %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= render partial: 'paggy' %>
  </div>
<% end %>

app/views/users/todo_lists/index.html.erb
<% if current_user %>
  <div class="container mt-4" style="width: 100%;">
    <div class="d-flex justify-content-between mb-4">
      <span class="btn btn-info">Today: <%= @today %></span>

      <div class="btn-group" role="group">
        <%= link_to "Incomplete Todo-Lists", incomplete_path, class: "btn btn-outline-primary" %>
        <%= link_to "New Todo-List", new_todo_list_path, class: "btn btn-primary" %>
      </div>
    </div>

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <td scope="col"><b>Title</b></td>
          <td scope="col"><b>Description</b></td>
          <td scope="col"><b>Action</b></td>
          <td scope="col"><b>Status</b></td>
        </tr>
      </thead>

      <tbody>
        <% @todo_lists.each do |list| %>
          <tr>
            <%= render partial: "todo_list_title", locals: { list: list } %>
            <%= render partial: "todo_list_description", locals: { list: list } %>
            <%= render partial: "todo_list_action", locals: { list: list } %>
            <%= render partial: "todo_list_status", locals: { list: list } %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= render partial: 'paggy' %>
  </div>
<% end %>

app/views/users/todo_lists/new.html.erb
<div class="col">
  <div class="d-flex row justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/users/todo_lists/show.html.erb
<div class="col">
  <div class="row justify-content-center">
    <div class="card" style="width: 70%;">
      <div class="card-header mb-2">
        <h2>
          <span class="pr-2">
            <i class="fas fa-clipboard-list"></i>
          </span>
          <%= @todo_list.title %>
        </h2>
      </div>

      <div class="card-body">
        <div class="mb-4">
          <%= @todo_list.description %>
        </div>
        
        <div id="todo_items_wrapper">
          <h5 class="mb-4">
            <i class="fas fa-tasks pr-2"></i>
            Tasks
          </h5>

          <%= render @todo_list.todo_items.order(:completed, created_at: :desc) %>
          <div id="form">
            <%= render "users/todo_items/form" %>
          </div>
        </div>

        <div>
          <% if @todo_list.completed == false %>
            <%= form_for(@todo_list) do |f| %>
              <%= f.check_box :completed, checked: true, hidden: true %>
              <%= f.submit "Mark Todo-List Completed", class: "btn btn-success btn-sm" %>
            <% end %>
          <% elsif @todo_list.completed == true %>
            <%= form_for(@todo_list) do |f| %>
              <%= f.check_box :completed, checked: false, hidden: true %>
              <%= f.submit "Mark Todo-List Incomplete", class: "btn btn-warning btn-sm" %>
            <% end %>
          <% end %>
        </div>
      </div>


      <div class="card-footer">
        <div class="row justify-content-between mx-auto">
          <div>
            <%= link_to "Edit", edit_todo_list_path, class: "btn btn-info" %>
            <%= link_to "Back", todo_lists_path, class: "btn btn-secondary" %>
          </div>
          <%= link_to "Delete", todo_list_path, method: "DELETE", data: { cofirm: "Are you sure?" }, class: "btn btn-danger" %>
        </div>
      </div>
     </div>
  </div>
</div>